#!/bin/sh

TESTFILE="$AUTOPKGTEST_TMP/foo"

touch "$TESTFILE"

if setfacl -m u:root:r "$TESTFILE"; then
  echo "Temporary directory '$AUTOPKGTEST_TMP' has ACLs enabled, running tests"
  export TEST_DIR="$AUTOPKGTEST_TMP"
  echo "* testing Python 3"
  python3 tests/test_acls.py
else
  echo "Temporary directory '$AUTOPKGTEST_TMP' doesn't have extended attributes enabled"
  echo "Skipping the tests :("
fi
